spring.application.name=tiendaMia
server.servlet.context-path=/tiendaMia
server.port=8089
#PostgresSQl
spring.datasource.url=jdbc:postgresql://localhost:5432/tienda_mia_db
spring.datasource.username=andrewchiroque
spring.datasource.password=""
spring.datasource.driver-class-name=org.postgresql.Driver

#creaccion
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
